import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "./_components/theme-provider";

import "@myapp/ui/globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="flex flex-col max-w-2xl mx-auto m-4 gap-4">
            {children}
          </main>
        </ThemeProvider>
        <div className="fixed bottom-0 p-2 flex justify-center items-center w-full">
          <h2 className="text-slate-500">
            Generated with{" "}
            <Link
              href="https://kiln-app.com"
              className="underline dark:hover:text-slate-400 hover:text-slate-600"
            >
              create-kiln-app
            </Link>
          </h2>
        </div>
      </body>
    </html>
  );
}
